package section09_Spring.topic07_SpringSecurityPart2.practice.SpringSecurityPartTwo.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class SecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
