package section09_Spring.topic09_SpringSecurityPart3.theory.T01_Stateless.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class WebSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
