package Hibernate.topic03_JPAAndCascadeTypes.HibernateCascade.dao.impl;

import Hibernate.topic03_JPAAndCascadeTypes.HibernateCascade.dao.AbstractTest;
import section08_Hibernate.topic03_JPAAndCascadeTypes.practice.HibernateCascade.dao.SmileDao;
import section08_Hibernate.topic03_JPAAndCascadeTypes.practice.HibernateCascade.dao.impl.SmileDaoImpl;
import section08_Hibernate.topic03_JPAAndCascadeTypes.practice.HibernateCascade.model.Smile;
import java.util.List;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class SmileDaoImplTest extends AbstractTest {
    private SmileDao smileDao;

    @Before
    public void setUp() {
        smileDao = new SmileDaoImpl(getSessionFactory());
    }

    @Override
    protected Class<?>[] entities() {
        return new Class<?>[]{
                Smile.class
        };
    }

    @Test
    public void create_Ok() {
        Smile funny = new Smile("funny");
        Smile actual = smileDao.create(funny);
        Assert.assertNotNull("Check you have implemented the `create` method " +
                "in the SmileDaoImpl class", actual);
        Assert.assertNotNull("ID for smile should be autogenerated", actual.getId());
        Assert.assertEquals(1L, actual.getId().longValue());
    }

    @Test
    public void getAll_Ok() {
        Smile funny = new Smile("funny");
        Smile sad = new Smile("sad");
        Smile relieved = new Smile("relieved");
        Smile disappointed = new Smile("disappointed");

        smileDao.create(funny);
        smileDao.create(sad);
        smileDao.create(relieved);
        smileDao.create(disappointed);

        List<Smile> smiles = smileDao.getAll();
        Assert.assertNotNull(smiles);
        Assert.assertFalse(smiles.isEmpty());
        Assert.assertEquals(4, smiles.size());
        System.out.println(smiles);
    }
}
