package section09_Spring.topic07_SpringSecurityPart2.theory.T02_ConfigureDBAuthentication.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class WebSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
