package section09_Spring.topic06_SpringSecurityPart1.theory.T02_StartSecurityConfiguration.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class WebSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
