package section09_Spring.topic09_SpringSecurityPart3.theory.T02_JWT.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class WebSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
