package section09_Spring.topic10_SpringTesting.theory.T01_HowToTestServices.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class WebSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
