package section09_Spring.topic06_SpringSecurityPart1.practice.SpringSecurity.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class WebSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}