package section09_Spring.topic09_SpringSecurityPart3.practice.SpringStateless.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class WebSecurityInitializer extends AbstractSecurityWebApplicationInitializer {

}
